import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-groups',
  templateUrl: './groups.component.html',
  styleUrls: ['./groups.component.css']
})
export class GroupsComponent implements OnInit {
  users=[
    {
      "first_name":"abc",
      "last_name":"vvv",
      "email":"abc@gdhd.com",
      "emp_id":3684694,
      "phone":7493684694,
      "groups_count":6,
      "profile_picture":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8hW4RqfgehYPGCdCeuWFsNhu-nDj_HGMzpavflfPUst1f_7FNfQ",
    },
    {
      "first_name":"fgrdt",
      "last_name":"vrtgertvv",
      "email":"ertertert@gdhd.com",
      "emp_id":345345,
      "phone":749345346,
      "groups_count":3,
      "profile_picture":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8hW4RqfgehYPGCdCeuWFsNhu-nDj_HGMzpavflfPUst1f_7FNfQ",
    },
    {
      "first_name":"drgteryt",
      "last_name":"eryeryery",
      "email":"dfhdhdfh@gdhd.com",
      "emp_id":46456,
      "phone":436457,
      "groups_count":2,
      "profile_picture":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8hW4RqfgehYPGCdCeuWFsNhu-nDj_HGMzpavflfPUst1f_7FNfQ",
    },
    {
      "first_name":"fgrdt",
      "last_name":"vrtgertvv",
      "email":"ertertert@gdhd.com",
      "emp_id":345345,
      "phone":749345346,
      "groups_count":3,
      "profile_picture":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8hW4RqfgehYPGCdCeuWFsNhu-nDj_HGMzpavflfPUst1f_7FNfQ",
    },
    {
      "first_name":"drgteryt",
      "last_name":"eryeryery",
      "email":"dfhdhdfh@gdhd.com",
      "emp_id":46456,
      "phone":436457,
      "groups_count":2,
      "profile_picture":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8hW4RqfgehYPGCdCeuWFsNhu-nDj_HGMzpavflfPUst1f_7FNfQ",
    }
    ,
    {
      "first_name":"fgrdt",
      "last_name":"vrtgertvv",
      "email":"ertertert@gdhd.com",
      "emp_id":345345,
      "phone":749345346,
      "groups_count":3,
      "profile_picture":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8hW4RqfgehYPGCdCeuWFsNhu-nDj_HGMzpavflfPUst1f_7FNfQ",
    },
    {
      "first_name":"drgteryt",
      "last_name":"eryeryery",
      "email":"dfhdhdfh@gdhd.com",
      "emp_id":46456,
      "phone":436457,
      "groups_count":2,
      "profile_picture":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8hW4RqfgehYPGCdCeuWFsNhu-nDj_HGMzpavflfPUst1f_7FNfQ",
    }
    ,
    {
      "first_name":"fgrdt",
      "last_name":"vrtgertvv",
      "email":"ertertert@gdhd.com",
      "emp_id":345345,
      "phone":749345346,
      "groups_count":3,
      "profile_picture":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8hW4RqfgehYPGCdCeuWFsNhu-nDj_HGMzpavflfPUst1f_7FNfQ",
    },
    {
      "first_name":"drgteryt",
      "last_name":"eryeryery",
      "email":"dfhdhdfh@gdhd.com",
      "emp_id":46456,
      "phone":436457,
      "groups_count":2,
      "profile_picture":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8hW4RqfgehYPGCdCeuWFsNhu-nDj_HGMzpavflfPUst1f_7FNfQ",
    }
    ,
    {
      "first_name":"fgrdt",
      "last_name":"vrtgertvv",
      "email":"ertertert@gdhd.com",
      "emp_id":345345,
      "phone":749345346,
      "groups_count":3,
      "profile_picture":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8hW4RqfgehYPGCdCeuWFsNhu-nDj_HGMzpavflfPUst1f_7FNfQ",
    },
    {
      "first_name":"drgteryt",
      "last_name":"eryeryery",
      "email":"dfhdhdfh@gdhd.com",
      "emp_id":46456,
      "phone":436457,
      "groups_count":2,
      "profile_picture":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8hW4RqfgehYPGCdCeuWFsNhu-nDj_HGMzpavflfPUst1f_7FNfQ",
    }
    ,
    {
      "first_name":"fgrdt",
      "last_name":"vrtgertvv",
      "email":"ertertert@gdhd.com",
      "emp_id":345345,
      "phone":749345346,
      "groups_count":3,
      "profile_picture":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8hW4RqfgehYPGCdCeuWFsNhu-nDj_HGMzpavflfPUst1f_7FNfQ",
    },
    {
      "first_name":"drgteryt",
      "last_name":"eryeryery",
      "email":"dfhdhdfh@gdhd.com",
      "emp_id":46456,
      "phone":436457,
      "groups_count":2,
      "profile_picture":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8hW4RqfgehYPGCdCeuWFsNhu-nDj_HGMzpavflfPUst1f_7FNfQ",
    }
    ,
    {
      "first_name":"fgrdt",
      "last_name":"vrtgertvv",
      "email":"ertertert@gdhd.com",
      "emp_id":345345,
      "phone":749345346,
      "groups_count":3,
      "profile_picture":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8hW4RqfgehYPGCdCeuWFsNhu-nDj_HGMzpavflfPUst1f_7FNfQ",
    },
    {
      "first_name":"drgteryt",
      "last_name":"eryeryery",
      "email":"dfhdhdfh@gdhd.com",
      "emp_id":46456,
      "phone":436457,
      "groups_count":2,
      "profile_picture":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8hW4RqfgehYPGCdCeuWFsNhu-nDj_HGMzpavflfPUst1f_7FNfQ",
    }
  ]

  groups=[
    {
      
    }
  ]
  constructor() { }

  ngOnInit() {
  }
  updateUi(){

  }

}